In [2]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
%matplotlib inline

In [3]:
# read in all the words
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [15]:
C = torch.randn((27, 2))
C.shape

torch.Size([27, 2])

In [6]:
# build the dataset
block_size = 3 # context length: how many characters do we take to predict the next one?


X, Y = [], []
for w in words[:5]:

  #print(w)
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append

X = torch.tensor(X)
Y = torch.tensor(Y)
print(X.shape, Y.shape)


... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
... ---> a
..a ---> v
.av ---> a
ava ---> .
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .
torch.Size([32, 3]) torch.Size([32])


In [7]:
X.shape

torch.Size([32, 3])

In [8]:
context

[9, 1, 0]

In [18]:
C[X]


tensor([[[-1.0140,  0.2307],
         [-1.0140,  0.2307],
         [-1.0140,  0.2307]],

        [[-1.0140,  0.2307],
         [-1.0140,  0.2307],
         [ 0.1405,  1.0665]],

        [[-1.0140,  0.2307],
         [ 0.1405,  1.0665],
         [ 1.3503, -0.4310]],

        [[ 0.1405,  1.0665],
         [ 1.3503, -0.4310],
         [ 1.3503, -0.4310]],

        [[ 1.3503, -0.4310],
         [ 1.3503, -0.4310],
         [ 0.6659, -0.5109]],

        [[-1.0140,  0.2307],
         [-1.0140,  0.2307],
         [-1.0140,  0.2307]],

        [[-1.0140,  0.2307],
         [-1.0140,  0.2307],
         [-0.2516, -0.1689]],

        [[-1.0140,  0.2307],
         [-0.2516, -0.1689],
         [ 0.1480,  0.9402]],

        [[-0.2516, -0.1689],
         [ 0.1480,  0.9402],
         [ 0.1888, -2.4088]],

        [[ 0.1480,  0.9402],
         [ 0.1888, -2.4088],
         [ 0.6915,  0.0081]],

        [[ 0.1888, -2.4088],
         [ 0.6915,  0.0081],
         [ 0.1888, -2.4088]],

        [[ 0.6915,  0

In [20]:
X.shape


torch.Size([32, 3])

In [23]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [25]:

torch.cat([emb[:, 0, :],emb[:, 1, :],emb[:, 2, :]],1) # select 2nd dimensions 3 columns explicitly and changes int to 2d

tensor([[-1.0140,  0.2307, -1.0140,  0.2307, -1.0140,  0.2307],
        [-1.0140,  0.2307, -1.0140,  0.2307,  0.1405,  1.0665],
        [-1.0140,  0.2307,  0.1405,  1.0665,  1.3503, -0.4310],
        [ 0.1405,  1.0665,  1.3503, -0.4310,  1.3503, -0.4310],
        [ 1.3503, -0.4310,  1.3503, -0.4310,  0.6659, -0.5109],
        [-1.0140,  0.2307, -1.0140,  0.2307, -1.0140,  0.2307],
        [-1.0140,  0.2307, -1.0140,  0.2307, -0.2516, -0.1689],
        [-1.0140,  0.2307, -0.2516, -0.1689,  0.1480,  0.9402],
        [-0.2516, -0.1689,  0.1480,  0.9402,  0.1888, -2.4088],
        [ 0.1480,  0.9402,  0.1888, -2.4088,  0.6915,  0.0081],
        [ 0.1888, -2.4088,  0.6915,  0.0081,  0.1888, -2.4088],
        [ 0.6915,  0.0081,  0.1888, -2.4088,  0.6659, -0.5109],
        [-1.0140,  0.2307, -1.0140,  0.2307, -1.0140,  0.2307],
        [-1.0140,  0.2307, -1.0140,  0.2307,  0.6659, -0.5109],
        [-1.0140,  0.2307,  0.6659, -0.5109,  0.6915,  0.0081],
        [ 0.6659, -0.5109,  0.6915,  0.0

In [27]:
torch.cat([emb[:, 0, :],emb[:, 1, :],emb[:, 2, :]],1).shape #[32,3,2] = 32,6

torch.Size([32, 6])

In [28]:
#without explicitly stating
torch.cat(torch.unbind(emb , 1), 1).shape #select 2nd D and convert

torch.Size([32, 6])

In [29]:
a = torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [30]:
a.view(3,3,2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])